version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  api:
    build: .
    env_file:
      - .env.dev
    ports: 
      - "8000:8000"
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./bin/server
