version: "3.7"

services:
  pg:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    env_file:
      - .env.dev
    depends_on:
     - pg
    command: /root/wait-for-it.sh pg:5432 -- /root/entrypoint.sh

  api:
    build: .
    env_file:
      - .env.dev
    ports: 
      - "8000:8000"
    depends_on:
      - pg
    command: /app/wait-for-it.sh pg:5432 -- /app/bin/server

volumes:
  postgres-data:
