version: "3.9"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.dev
    
  api:
    build: .
    env_file:
      - .env.dev
    ports: 
      - "8000:8000"
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./bin/server
