version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    
  api:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - db
    #TODO: Deal with permissions
    command: sh -c './wait-for-it.sh db:5432 -- ./bin/server'
